const express=require("express");
const { getAllProducts, createProduct, getProductById, updateProduct, deleteProduct, getProductsByCategory } = require("../controllers/productController");
const router=express.Router();
router.get('/',getAllProducts);
router.post('/',createProduct);
router.get('/:id',getProductById);
router.put('/:id',updateProduct);
router.delete('/:id',deleteProduct);
router.get('/category/:category_id',getProductsByCategory);
module.exports=router;